project1/answer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from . import views

app_name = 'answer'
urlpatterns = [
    url(r'^(?P<question_id>[0-9]+)/create/$', views.AnswerCreate.as_view(), name='create'),
]

project1/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^login/', LoginView.as_view(template_name = 'core/login.html'), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^question/', include('question.urls')),
    url(r'^anwer/', include('answer.urls')),
]

project1/project1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
]

project1/question/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from . import views

app_name = 'question'
urlpatterns = [
    url(r'^$', views.QuestionList.as_view(), name='question_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(), name='question_detail'),
    url(r'^create/$', views.QuestionCreate.as_view(), name='question_create'),
    url(r'^(?P<pk>[0-9]+)/ajax/$', views.QuestionDetailAjax.as_view(), name='question_answers'),
]

project1/answer/models.py
from django.db import models

from django.conf import settings
from question.models import Question

class Answer(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.TextField()
    date_create = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text[:255]

    class Meta:
        ordering = ('-date_create',)

project1/category/models.py
from django.db import models

class Category(models.Model):
    name_category = models.CharField(max_length=512)
    
    def __str__(self):
        return self.name_category

    class Meta:
        ordering = ('name_category',)

project1/core/models.py
from django.db import models

# Create your models here.

project1/question/models.py
from django.db import models

from django.conf import settings
from category.models import Category

class Question(models.Model):
    question_text = models.TextField()
    category = models.ForeignKey(Category, related_name='questions', on_delete=models.SET_NULL, null=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_text[:255]
    
    class Meta:
       ordering = ('-pub_date',)
 

project1/question/forms.py
from django import forms
from .models import Question

class QuestionListForm(forms.Form):
    search = forms.CharField(required=False)
    sort_field = forms.ChoiceField(choices=(('pub_date', 'Дата публикации'), ('autor', 'Автор'), ('category', 'Категория')))

#class QuestionForm(forms.ModelForm):
#    
#    class Meta:
#        model = Question
    

project1/answer/views.py
from django.shortcuts import render, resolve_url

from .models import Answer
from question.models import Question
from django.views.generic import CreateView

class AnswerCreate(CreateView):
    model = Answer
    template_name = 'answer/create.html'
    fields = ['text']

    def form_valid(self, form):
        print("!!", self.kwargs['question_id'])
        form.instance.autor = self.request.user
        form.instance.question = Question.objects.get(pk=self.kwargs['question_id'])
        return super(AnswerCreate, self).form_valid(form)

    def get_success_url(self):
        return resolve_url('core:question:question_detail', pk=Question.objects.get(pk=self.kwargs['question_id']).pk)

project1/category/views.py
from django.shortcuts import render

# Create your views here.

project1/core/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from question.models import Question
from answer.models import Answer
from category.models import Category

def index(request):
    latest_categories_list = Category.objects.all()[:5]
    latest_questions_list = Question.objects.all()[:5]
    latest_answers_list = Answer.objects.all()[:5]

    context = {'latest_categories_list': latest_categories_list, 
                'latest_questions_list': latest_questions_list, 
                'latest_answers_list': latest_answers_list}

    return render(request, 'core/index.html', context)

project1/question/views.py
from django.shortcuts import render, resolve_url
from django.views.generic import ListView, DetailView, CreateView
from .models import Question
from .forms import QuestionListForm

class QuestionList(ListView):
    model = Question
    template_name = 'question/question_list.html'
    context_object_name = 'question_list'
    
    def dispatch(self, request, *args, **kwargs):
        self.form = QuestionListForm(request.GET)
        self.form.is_valid()
        return super(QuestionList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Question.objects.all()
        if self.form.cleaned_data.get('search'):
            queryset = queryset.filter(question_text__icontains=self.form.cleaned_data['search'])
        if self.form.cleaned_data.get('sort_field'):
            queryset = queryset.order_by(self.form.cleaned_data['sort_field'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(QuestionList, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context

class QuestionDetailAjax(DetailView):
    template_name = "question/question_detail_ajax.html"
    model = Question
    context_object_name = "question"

class QuestionDetail(DetailView):
    model = Question
    template_name = 'question/question_detail.html'
    context_object_name = 'question'
    
class QuestionCreate(CreateView):
    model = Question
    template_name = 'question/create.html'
    fields = ['question_text', 'category']

#    def dispatch(self, request, *args, **kwars):
#        self.form = QuestionForm(request.POST)
#        self.form.is_valid()
#        return super(QuestionCreate, self).dispatch(request, *args, **kwargs)

#    def get_context_data(self, **kwargs):
#        context = super(QuestionCreate, self).get_context_data(**kwargs)
#        context['form'] = self.form
#        return context

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super(QuestionCreate, self).form_valid(form)

    def get_success_url(self):
        return resolve_url('core:question:question_detail', pk=self.object.pk)

project1/answer/templates/answer/create.html
{% extends "core/base.html" %}

{% block title %}Создание ответа{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    {% else %}
        Чтобы ответить, вначале войдите в систему!
    {% endif%}
{% endblock %}

project1/core/templates/core/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'core:home' %}">Здесь должно быть лого:)</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home' %}">На главную <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:question:question_list' %}">Все вопросы</a>
          </li>
	  <li class="nav-item">
            <a class="nav-link" href="{% url 'core:question:question_create'%}">Создать вопрос</a>
          </li>
          <li class="nav-item">
          {% if user.is_authenticated %}

<form class="form-inline my-2 my-lg-0">
              <span style="color: white;">{{ user }}</span> <a class="nav-link" href="{% url 'core:logout' %}"?next={{ request.path }}>Выйти</a>
</form>

          {% else %}

              <a class="nav-link" href="{% url 'core:login' %}"?next={{ request.path }}>Войти</a>

          {% endif %}
          </li>  


      </div>
    </nav>


    
<main role="main" class="container">

	<br><br><br><br>
      <div class="starter-template">
        {% block content %}{% endblock %}
      </div>

    </main>


</body>

</html>

project1/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div>
        Категории<hr>
        {% for x in latest_categories_list %}
            {{ x }} <hr>
        {% endfor %}
    </div>

    </br></br>

    <div>
        Последние вопросы<hr>
        {% for x in latest_questions_list %}
            {{ x.autor }} {{ x.pub_date }} <a href="/question/{{ x.id }}">{{ x.question_text }}</a><hr>
        {% endfor %}
    </div>

    </br></br>

    <div>
        Последние ответы<hr>
        {% for x in latest_answers_list %}
            {{ x.autor }} {{ x.date_create}}</br>
            {{ x.text }}<hr>
        {% endfor %}
    </div>

{% endblock %}

project1/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Войти на сайт{% endblock %}

{% block content%}
    {% if user.is_authenticated %}
        Вы уже в системе!
    {% else %}
    <form method="POST"">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form> 
    {% endif %}
{% endblock %}

project1/question/templates/question/create.html
{% extends "core/base.html" %}

{% block title %}Создание нового вопроса{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    {% else %}
        Чтобы задать вопрос, вначале войдите в систему!
    {% endif%}
{% endblock %}

project1/question/templates/question/question_detail.html
{% extends "core/base.html" %}

{% block title%}Вопрос №{{ question.id }}{% endblock %}

{% block content%}
    Вопрос</br>
    {{ question.category }}
    {{ question.pub_date }}
    {{ question.autor }}</br></br>
    {{ question.question_text }}</br></br>
    
    Ответы</br>
    <div id="answers">
    </div>

    <a href={% url 'core:answer:create' question.pk %}>Ответить</a>

    <script>
        function load_answers() {
            $('#answers').load('{% url "core:question:question_answers" pk=question.pk %}');
        }
        window.setInterval(load_answers, 1000)
    </script>
{% endblock %}

project1/question/templates/question/question_detail_ajax.html
{% for x in question.answers.all %}
    {{ x }}<hr>
{% endfor %}

project1/question/templates/question/question_list.html
{% extends "core/base.html" %}

{% block title %}Список всех вопросов{% endblock %}

{% block content %}

    <form action="" method="GET">
        Поиск: 
        {{ form.search }}
        Сортировать по: 
        {{ form.sort_field }}
        <input type="submit">
    </form>

    {% for x in question_list %}
        <div class="question">
            {{ x.autor }} {{ x.pub_date }} <a href="/question/{{ x.id }}">{{ x.question_text }}</a> {{ x.category }}>
        </div>
    {% endfor %}
{% endblock %}